export interface EconomicEvent {
    date: string;           // YYYY-MM-DD
    time: string;           // HH:MM ET
    name: string;           // "FOMC Rate Decision"
    country: 'US' | 'UK';
    impact: 'high' | 'medium' | 'low';
    category: string;       // "central_bank", "employment", "inflation", "gdp"
    estimated?: boolean;    // true when the date is rule-derived, not officially scheduled
}

/**
 * Known central-bank decision dates (officially scheduled). These DO expire —
 * refresh annually when the Fed / BoE publish the next year's schedule. The
 * monthly releases below (NFP/CPI) are generated by rule so the calendar never
 * goes empty between refreshes.
 */
const CENTRAL_BANK_DATES: EconomicEvent[] = [
    // US FOMC 2026
    { date: '2026-01-28', time: '14:00', name: 'FOMC Rate Decision', country: 'US', impact: 'high', category: 'central_bank' },
    { date: '2026-03-18', time: '14:00', name: 'FOMC Rate Decision', country: 'US', impact: 'high', category: 'central_bank' },
    { date: '2026-05-06', time: '14:00', name: 'FOMC Rate Decision', country: 'US', impact: 'high', category: 'central_bank' },
    { date: '2026-06-17', time: '14:00', name: 'FOMC Rate Decision', country: 'US', impact: 'high', category: 'central_bank' },
    { date: '2026-07-29', time: '14:00', name: 'FOMC Rate Decision', country: 'US', impact: 'high', category: 'central_bank' },
    { date: '2026-09-16', time: '14:00', name: 'FOMC Rate Decision', country: 'US', impact: 'high', category: 'central_bank' },
    { date: '2026-11-04', time: '14:00', name: 'FOMC Rate Decision', country: 'US', impact: 'high', category: 'central_bank' },
    { date: '2026-12-16', time: '14:00', name: 'FOMC Rate Decision', country: 'US', impact: 'high', category: 'central_bank' },
    // UK BoE 2026
    { date: '2026-02-05', time: '07:00', name: 'BOE Interest Rate Decision', country: 'UK', impact: 'high', category: 'central_bank' },
    { date: '2026-03-26', time: '07:00', name: 'BOE Interest Rate Decision', country: 'UK', impact: 'high', category: 'central_bank' },
    { date: '2026-05-07', time: '07:00', name: 'BOE Interest Rate Decision', country: 'UK', impact: 'high', category: 'central_bank' },
    { date: '2026-06-18', time: '07:00', name: 'BOE Interest Rate Decision', country: 'UK', impact: 'high', category: 'central_bank' },
    { date: '2026-08-06', time: '07:00', name: 'BOE Interest Rate Decision', country: 'UK', impact: 'high', category: 'central_bank' },
    { date: '2026-09-17', time: '07:00', name: 'BOE Interest Rate Decision', country: 'UK', impact: 'high', category: 'central_bank' },
    { date: '2026-11-05', time: '07:00', name: 'BOE Interest Rate Decision', country: 'UK', impact: 'high', category: 'central_bank' },
    { date: '2026-12-17', time: '07:00', name: 'BOE Interest Rate Decision', country: 'UK', impact: 'high', category: 'central_bank' },
];

function iso(d: Date): string {
    return d.toISOString().slice(0, 10);
}

/** First Friday of a month (UTC) — the BLS Employment Situation / NFP release. */
function firstFriday(year: number, monthIdx: number): string {
    const d = new Date(Date.UTC(year, monthIdx, 1));
    const offset = (5 - d.getUTCDay() + 7) % 7; // 5 = Friday
    d.setUTCDate(1 + offset);
    return iso(d);
}

/** Estimated mid-month weekday — BLS CPI usually lands ~10th–14th. */
function midMonthWeekday(year: number, monthIdx: number): string {
    const d = new Date(Date.UTC(year, monthIdx, 13));
    const day = d.getUTCDay();
    if (day === 0) d.setUTCDate(14);      // Sun → Mon
    else if (day === 6) d.setUTCDate(15); // Sat → Mon
    return iso(d);
}

/** Rule-generated monthly US releases (NFP exact, CPI estimated) for N months. */
function generateMonthlyReleases(from: Date, monthsAhead: number): EconomicEvent[] {
    const events: EconomicEvent[] = [];
    for (let i = 0; i <= monthsAhead; i++) {
        const y = from.getUTCFullYear();
        const m = from.getUTCMonth() + i;
        const year = y + Math.floor(m / 12);
        const monthIdx = ((m % 12) + 12) % 12;
        events.push({
            date: firstFriday(year, monthIdx), time: '08:30', name: 'Non-Farm Payrolls',
            country: 'US', impact: 'high', category: 'employment',
        });
        events.push({
            date: midMonthWeekday(year, monthIdx), time: '08:30', name: 'Core CPI (est.)',
            country: 'US', impact: 'high', category: 'inflation', estimated: true,
        });
    }
    return events;
}

export class EconomicCalendarService {
    /** All known + generated events, deduped by date+name, chronological. */
    private static allEvents(): EconomicEvent[] {
        const generated = generateMonthlyReleases(new Date(), 4);
        const seen = new Set<string>();
        const merged: EconomicEvent[] = [];
        for (const e of [...CENTRAL_BANK_DATES, ...generated]) {
            const key = `${e.date}|${e.name}`;
            if (seen.has(key)) continue;
            seen.add(key);
            merged.push(e);
        }
        return merged.sort((a, b) => a.date.localeCompare(b.date));
    }

    static getUpcomingEvents(days = 14): EconomicEvent[] {
        const now = new Date();
        const today = iso(now);
        const end = iso(new Date(now.getTime() + days * 86_400_000));
        return this.allEvents().filter(e => e.date >= today && e.date <= end);
    }

    static getEventsForDate(date: string): EconomicEvent[] {
        return this.allEvents().filter(e => e.date === date);
    }

    static isHighImpactDay(date: string): boolean {
        return this.getEventsForDate(date).some(e => e.impact === 'high');
    }

    static getNextFOMC(): EconomicEvent | null {
        const today = iso(new Date());
        return CENTRAL_BANK_DATES
            .filter(e => e.name === 'FOMC Rate Decision' && e.date >= today)
            .sort((a, b) => a.date.localeCompare(b.date))[0] ?? null;
    }

    static getNextBOE(): EconomicEvent | null {
        const today = iso(new Date());
        return CENTRAL_BANK_DATES
            .filter(e => e.name === 'BOE Interest Rate Decision' && e.date >= today)
            .sort((a, b) => a.date.localeCompare(b.date))[0] ?? null;
    }
}
